{{- if .Values.secret.create }}
{{- if .Values.secret.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "doris-webhook.secretName" . }}
  labels:
    {{- include "doris-webhook.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.secret.password | b64enc | quote }}
{{- end }}
{{- end }}

